@echo off

set ORDER_DATA_SOURCE_URL=root:root@tcp(localhost:3306)/orders
set ORDER_APPLICATION_PORT=8089
set ORDER_ENV=dev
set ORDER_PAYMENT_SERVICE_URL=localhost:8088



echo ORDER_APPLICATION_PORT=%ORDER_APPLICATION_PORT%
echo ORDER_ENV=%ORDER_ENV%
echo ORDER_DATA_SOURCE_URL=%ORDER_DATA_SOURCE_URL%
echo ORDER_PAYMENT_SERVICE_URL=%ORDER_PAYMENT_SERVICE_URL%


pause