@echo off

set PAYMENT_DATA_SOURCE_URL=root:root@tcp(localhost:3306)/orders
set PAYMENT_APPLICATION_PORT=8088
set PAYMENT_ENV=dev

echo PAYMENT_DATA_SOURCE_URL=%PAYMENT_DATA_SOURCE_URL%
echo PAYMENT_APPLICATION_PORT=%PAYMENT_APPLICATION_PORT%
echo PAYMENT_ENV=%PAYMENT_ENV%

pause